apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: project
spec:
  replicas: 5
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: myimage
        image: dhivya2409/PRT
        ports:
        - containerPort: 80    
